In [1]:
import torch

In [2]:
x = torch.arange(12)

In [3]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape

torch.Size([12])

In [5]:
x.numel()

12

In [6]:
X = x.reshape(3,4)

In [7]:
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
X.size()

torch.Size([3, 4])

In [10]:
X.numel()

12

In [11]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
torch.ones((3,5,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [16]:
torch.randn(3,4)

tensor([[-0.8268, -0.5099,  1.0772, -0.0693],
        [-0.0813, -1.3067, -1.0315,  0.4708],
        [ 0.0310, -0.3275, -1.1602,  0.2046]])

In [21]:
A = torch.tensor([[[2,1,3,4],[5,4,6,7],[7,4,8,6]]])

In [22]:
A

tensor([[[2, 1, 3, 4],
         [5, 4, 6, 7],
         [7, 4, 8, 6]]])

In [23]:
A.size()

torch.Size([1, 3, 4])

### Operations

In [24]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])

In [25]:
x+y,x-y,x*y,x/y,x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [26]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [36]:
X = torch.arange(12, dtype = torch.float32).reshape(3,4)
Y = torch.tensor([[2,3,4,3],[5,4,8,9],[4,5,8,3]])

In [37]:
torch.cat((X,Y), dim = 0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  3.,  4.,  3.],
        [ 5.,  4.,  8.,  9.],
        [ 4.,  5.,  8.,  3.]])

In [38]:
torch.cat((X,Y), dim = 1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  3.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  5.,  4.,  8.,  9.],
        [ 8.,  9., 10., 11.,  4.,  5.,  8.,  3.]])

In [39]:
X == Y

tensor([[False, False, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [41]:
X.sum()

tensor(66.)

### Brodcasting

In [42]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape(1,2)

In [43]:
a

tensor([[0],
        [1],
        [2]])

In [44]:
b

tensor([[0, 1]])

In [45]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### Indexing and Slicing

In [46]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [47]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]), tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [49]:
X[-1,0], X[1:3,2]

(tensor(8.), tensor([ 6., 10.]))

### Saving Memory

In [52]:
before = id(Y)
Y = Y+X
id(Y) == before

False

In [57]:
Z = torch.zeros_like(Y)
print('ID:{}'.format(id(Z)))
Z[:] = X+Y
print('ID:{}'.format(id(Z)))

ID:139763094194504
ID:139763094194504


In [58]:
before = id(X)
X +=Y
id(X) == before

True

### Conversion

In [59]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [64]:
a = torch.tensor([3.5])
a,a.item(),float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [65]:
X

tensor([[ 2.,  5.,  8.,  9.],
        [13., 14., 20., 23.],
        [20., 23., 28., 25.]])

In [66]:
Y

tensor([[ 2.,  4.,  6.,  6.],
        [ 9.,  9., 14., 16.],
        [12., 14., 18., 14.]])

In [67]:
X == Y

tensor([[ True, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [68]:
X>Y

tensor([[False,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [69]:
X<Y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])