In [1]:
import torch

In [28]:
X = torch.arange(1,6, dtype = torch.float32)

In [37]:
y = torch.ones(2,3,4)

In [45]:
y

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [35]:
X, y , torch.dot(X,y)

(tensor([1., 2., 3., 4., 5.]), tensor([1., 1., 1., 1., 1.]), tensor(15.))

In [36]:
y.size()

torch.Size([5])

In [53]:
y.sum(axis=0)

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

In [54]:
y.sum(axis=1)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [55]:
y.sum(axis=2)

tensor([[4., 4., 4.],
        [4., 4., 4.]])